// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtinyeclraupzeewqnyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10aW55ZWNscmF1cHplZXdxbnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MTY4MTksImV4cCI6MjA3MzA5MjgxOX0.AtnYNCipDTCe03flNEJSJ1EHh2IxmgjHjdyo6v90IvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});